name: Laravel API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: username
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        
    - name: Setup PHP
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: phpunit, prestissimo
        extensions: gd, json, mbstring, mysql, dom, fileinfo, xml, xsl, zip, curl, bcmath, intl
    
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --no-scripts --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Copy Laravel CI environment
      run: cp .env.ci .env

    - name: Generate Key
      run: php artisan key:generate

    - name: Run Migration
      run: php artisan migrate
      env:
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
    
    - name: Run Testsuite
      run: vendor/bin/phpunit
      env:
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
